name: multi_env_deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  print_input:
    runs-on: ubuntu-latest

    steps:
      - name: Print input
        run: echo "${{ inputs.name }}"
